# Generated by Django 4.2.6 on 2023-10-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_avtobus_dayanacaq_surucu_xett_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtobus',
            name='rezerv_surucu_1',
        ),
        migrations.RemoveField(
            model_name='avtobus',
            name='rezerv_surucu_2',
        ),
        migrations.RemoveField(
            model_name='avtobus',
            name='əsas_surucu_1',
        ),
        migrations.RemoveField(
            model_name='avtobus',
            name='əsas_surucu_2',
        ),
        migrations.AddField(
            model_name='avtobus',
            name='rezerv_sürücü_1',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='rezerv_sürücü_1_avtobuslar_üçün', to='busapp.surucu'),
        ),
        migrations.AddField(
            model_name='avtobus',
            name='rezerv_sürücü_2',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='rezerv_sürücü_2_avtobuslar_üçün', to='busapp.surucu'),
        ),
        migrations.AddField(
            model_name='avtobus',
            name='əsas_sürücü_1',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='əsas_sürücü_1_avtobuslar_üçün', to='busapp.surucu'),
        ),
        migrations.AddField(
            model_name='avtobus',
            name='əsas_sürücü_2',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='əsas_sürücü_2_avtobuslar_üçün', to='busapp.surucu'),
        ),
        migrations.AlterField(
            model_name='avtobus',
            name='avtobus_nömrəsi',
            field=models.CharField(default='Avtobus Nömrəsi', max_length=255),
        ),
        migrations.AlterField(
            model_name='avtobus',
            name='xett',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='busapp.xett'),
        ),
        migrations.AlterField(
            model_name='dayanacaq',
            name='ad',
            field=models.CharField(default='Dayanacaq Adı', max_length=255),
        ),
        migrations.AlterField(
            model_name='dayanacaq',
            name='interval',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dayanacaq',
            name='xett',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='busapp.xett'),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='ad',
            field=models.CharField(default='Sürücü Adı', max_length=255),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='istirahət_günü',
            field=models.DateField(default='2023-10-20'),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='saglamliq_veziyyeti',
            field=models.CharField(default='Sağlamlıq Vəziyyəti', max_length=255),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='təyin_edilmis_xettlər',
            field=models.ManyToManyField(default='Unknown', to='busapp.xett'),
        ),
        migrations.AlterField(
            model_name='xett',
            name='ad',
            field=models.CharField(default='Xett Adı', max_length=255),
        ),
        migrations.AlterField(
            model_name='xett',
            name='interval',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='xett',
            name='uzunluq',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='xett',
            name='vaxt_tamamlayici',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
