# Generated by Django 4.2.6 on 2023-10-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_alter_avtobus_rezerv_sürücü_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('route_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_to_complete', models.PositiveIntegerField()),
                ('stop_interval', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('health_condition', models.CharField(max_length=255)),
                ('days_off', models.DateField()),
                ('assigned_routes', models.ManyToManyField(to='busapp.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_interval', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.busroute')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayanacaq',
            name='xett',
        ),
        migrations.RemoveField(
            model_name='surucu',
            name='təyin_edilmis_xettlər',
        ),
        migrations.DeleteModel(
            name='Avtobus',
        ),
        migrations.DeleteModel(
            name='Dayanacaq',
        ),
        migrations.DeleteModel(
            name='Surucu',
        ),
        migrations.DeleteModel(
            name='Xett',
        ),
        migrations.AddField(
            model_name='bus',
            name='backup_driver_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_driver_1_for_buses', to='busapp.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='backup_driver_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_driver_2_for_buses', to='busapp.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='primary_driver_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_driver_1_for_buses', to='busapp.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='primary_driver_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_driver_2_for_buses', to='busapp.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.busroute'),
        ),
    ]
